import { NextRequest, NextResponse } from 'next/server';
import crypto from 'crypto';
import { db } from '@saru/db';
import { user, session } from '@saru/db';
import { eq } from 'drizzle-orm';

const ALLOWED_LOCALHOST_PORTS = ['3000', '3001'];

function isAllowedOrigin(referer: string | null): boolean {
  // Allow if referer is missing or stripped (e.g. window.open with noopener)
  if (!referer) return true;
  try {
    const url = new URL(referer);
    const hostname = url.hostname;
    const port = url.port;

    if (hostname === 'localhost' || hostname === '127.0.0.1') {
      return ALLOWED_LOCALHOST_PORTS.includes(port);
    }

    return hostname === 'myapps.ai' || hostname.endsWith('.myapps.ai');
  } catch {
    return false;
  }
}

/** Generate a random base62 ID matching better-auth style */
function generateId(length = 32): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  const bytes = crypto.randomBytes(length);
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars[bytes[i] % chars.length];
  }
  return result;
}

/**
 * Sign a cookie value using HMAC-SHA256 exactly as better-auth does internally.
 * better-auth's getSignedCookie expects: encodeURIComponent(`${value}.${btoa(hmacSha256(value, secret))}`)
 * The raw token is stored in DB; the signed value goes in the cookie.
 */
async function signCookieValue(value: string, secret: string): Promise<string> {
  const keyData = new TextEncoder().encode(secret);
  const cryptoKey = await crypto.webcrypto.subtle.importKey(
    'raw',
    keyData,
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const signatureBuffer = await crypto.webcrypto.subtle.sign(
    'HMAC',
    cryptoKey,
    new TextEncoder().encode(value)
  );
  const base64Signature = btoa(
    String.fromCharCode(...new Uint8Array(signatureBuffer))
  );
  return encodeURIComponent(`${value}.${base64Signature}`);
}

export async function GET(request: NextRequest) {
  // 1. Enforce Referer origin check (only reject if referer is present but disallowed)
  const referer = request.headers.get('referer');
  if (!isAllowedOrigin(referer)) {
    console.warn(`[SSO] Rejected: invalid referer: ${referer}`);
    return NextResponse.json({ error: 'Access denied: invalid origin' }, { status: 403 });
  }

  // 2. Extract and validate the SSO token
  const ssoToken = request.nextUrl.searchParams.get('sso_token');
  if (!ssoToken) {
    return NextResponse.json({ error: 'Missing sso_token parameter' }, { status: 400 });
  }

  const parts = ssoToken.split('.');
  if (parts.length !== 2) {
    return NextResponse.json({ error: 'Invalid SSO token format' }, { status: 400 });
  }

  const [subject, signature] = parts;
  const subParts = subject.split(':');
  if (subParts.length !== 2) {
    return NextResponse.json({ error: 'Invalid SSO token subject' }, { status: 400 });
  }

  const [userId, issuedAtStr] = subParts;
  const issuedAt = parseInt(issuedAtStr, 10);
  if (!userId || isNaN(issuedAt)) {
    return NextResponse.json({ error: 'Invalid SSO token parameters' }, { status: 400 });
  }

  // Check token age (5-minute window)
  const now = Math.floor(Date.now() / 1000);
  if (Math.abs(now - issuedAt) > 300) {
    return NextResponse.json({ error: 'SSO token expired' }, { status: 401 });
  }

  // Verify HMAC-SHA256 signature (generated by AiTutor wrapper using SCRIBE_SECRET_KEY)
  const ssoSecret = process.env.SCRIBE_SECRET_KEY;
  if (!ssoSecret) {
    return NextResponse.json({ error: 'SCRIBE_SECRET_KEY is not configured' }, { status: 500 });
  }

  const expectedSignature = crypto
    .createHmac('sha256', ssoSecret)
    .update(subject)
    .digest('hex');

  if (signature !== expectedSignature) {
    return NextResponse.json({ error: 'Invalid SSO token signature' }, { status: 401 });
  }

  // Need BETTER_AUTH_SECRET to sign the session cookie (better-auth verifies signed cookies)
  const authSecret = process.env.BETTER_AUTH_SECRET;
  if (!authSecret) {
    return NextResponse.json({ error: 'BETTER_AUTH_SECRET is not configured' }, { status: 500 });
  }

  try {
    // 3. Look up the user in Scribe's DB
    const [dbUser] = await db
      .select()
      .from(user)
      .where(eq(user.id, userId))
      .limit(1);

    if (!dbUser) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    // 4. Create a new session in the database
    //    better-auth stores the RAW token in the DB; the SIGNED version goes in the cookie
    const sessionToken = generateId(32);
    const sessionId = generateId(32);
    const now2 = new Date();
    const expiresAt = new Date(now2.getTime() + 30 * 24 * 60 * 60 * 1000); // 30 days

    await db.insert(session).values({
      id: sessionId,
      token: sessionToken,       // raw token stored in DB
      userId: dbUser.id,
      expiresAt,
      createdAt: now2,
      updatedAt: now2,
      ipAddress: request.headers.get('x-forwarded-for') ?? request.headers.get('x-real-ip') ?? '',
      userAgent: request.headers.get('user-agent') ?? '',
    });

    // 5. Sign the session token using BETTER_AUTH_SECRET (same as better-auth does internally)
    //    getSignedCookie splits on last '.', verifies base64 HMAC, returns raw token to look up in DB
    const signedTokenValue = await signCookieValue(sessionToken, authSecret);

    // Detect HTTPS environment
    const hostHeader = request.headers.get('x-forwarded-host') || request.headers.get('host') || 'scribe-pro.vercel.app';
    const isHttps = request.headers.get('x-forwarded-proto') === 'https' || (!hostHeader.includes('localhost') && !hostHeader.includes('127.0.0.1'));
    const isProduction = process.env.NODE_ENV === 'production' || isHttps;

    const redirectUrl = request.nextUrl.searchParams.get('next') || '/documents';
    const protocol = isHttps ? 'https' : 'http';
    const response = NextResponse.redirect(new URL(redirectUrl, `${protocol}://${hostHeader}`));

    const cookieExpires = expiresAt.toUTCString();

    // Set both cookie variants so it works regardless of which name better-auth checks first
    response.headers.append(
      'Set-Cookie',
      `better-auth.session_token=${signedTokenValue}; Path=/; HttpOnly; SameSite=Lax; Expires=${cookieExpires}${isProduction ? '; Secure' : ''}`
    );
    if (isHttps) {
      response.headers.append(
        'Set-Cookie',
        `__Secure-better-auth.session_token=${signedTokenValue}; Path=/; HttpOnly; SameSite=Lax; Secure; Expires=${cookieExpires}`
      );
    }

    console.log(`[SSO] User ${dbUser.email} logged in via SSO from ${referer}`);
    return response;
  } catch (err: any) {
    console.error('[SSO] Error:', err);
    return NextResponse.json({ error: err.message || 'Internal Server Error' }, { status: 500 });
  }
}
